### PR TITLE
Use urwid>=2.5.0 Scrollable and ScrollBar widgets (Fixes #244)

### LINKED ISSUE #244: urwid 2.4.2 and higher break stig
When stig wasn't working with the latest urwid, I tried several versions to pinpoint which had the breaking changes, which is 2.4.2

Trace: 
``
Traceback (most recent call last):
  File "/home/maarten/.local/bin/stig", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/__init__.py", line 25, in run
    main.run()
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/main.py", line 102, in run
    if not tui.run(run_commands):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/main.py", line 30, in run
    from . import tuiobjects
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/tuiobjects.py", line 107, in <module>
    logwidget = LogWidget(height=int(objects.localcfg['tui.log.height']),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/logger.py", line 45, in __init__
    self._scrollable = Scrollable(self._pile)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maarten/.local/pipx/venvs/stig/lib/python3.11/site-packages/stig/tui/scroll.py", line 46, in __init__
    raise ValueError('Not a fixed or flow widget: %r' % widget)
ValueError: Not a fixed or flow widget: <Pile widget>
``

### PR DESCRIPTION
**Pull request by rsekman**
The `Scrollable` and `ScrollBar` widgets implemented for stig were merged into urwid in 2.5.0. This PR updates stig to use the now native urwid widgets. This makes stig compatible with urwid>=2.5.0. However, this PR depends on https://github.com/urwid/urwid/pull/879 being merged and released. This is because stig tries to scroll widgets inside `AttrMap` in several places. After that bug is fixed, we'll need to bump the `urwid` requirement to whatever release it ends up in (likely 2.6.12), and then stig's version.

### CODE REVIEW

**Comment by rndusr** [comment]
Looks like this wasn't fixed yet. urwid 2.6.11 still gives me the "TypeError:
Not a scrollable widget" error.

If it is no trouble for you, could you ping me when the fix in urwid is
released?

**Comment by rsekman** [comment]
@rndusr  the needed code has now been merged and released in urwid 2.6.12 https://github.com/urwid/urwid/releases/tag/2.6.12

**Comment by rndusr** [comment]
Great, thank you very much!

I'll make a new release tomorrow if this keeps running smoothly.

If you are bored, I'm getting this warning:

    [...]/python3.11/site-packages/urwid/widget/grid_flow.py:81: GridFlowWarning: Size is smaller than cell width (-1 < 20)
      super().__init__(self.generate_display_widget((self._cache_maxcol,)))

It looks like it's caused by TabBar, which is the only widget using
GridFlow. (Aside from TorrentDetailsWidget, which shouldn't be created before
the TUI is running.)

It's ok if you don't care enough to fix this, me neither. :P

**Comment by rsekman** [comment]
That warning seems to be due to [an upstream change in urwid](https://github.com/urwid/urwid/pull/738/). `GridFlow` is now a flow widget and urwid now computes its width as `maxcols = N * width + (N-1) h_sep`, where `N` is the number of children. For an empty `GridFlow` we get `maxcols = -h_sep`. I think this is an issue in `urwid`; creating a container widget with no children should not raise a warning.

**Comment by rsekman** [comment]
I've [reported this upstream](https://github.com/urwid/urwid/issues/900).

**Comment by rsekman** [comment]
Fixed as of [urwid 2.6.14](https://github.com/urwid/urwid/releases/tag/2.6.14)

**Comment by rndusr** [comment]
Great!

Thanks again for doing my job. stig would be a lot deader without you.

**Pull request merged**
