### PR TITLE
README: Fix command to see help about configuration

### PR DESCRIPTION
**Pull request by inkch**
Tiny fix :)

### CODE REVIEW

**Comment by inkch** [comment]
```
$ python -V
Python 3.7.4

$ stig help cfgman
help: Unknown help topic: 'cfgman'
```

**Comment by rndusr** [comment]
Yeah, I changed the names of help topics (again :(), and I haven't released a
new version since.

https://pypi.python.org/pypi/stig is for the current release (although it seems
impossible to satisfy PyPI's rst parser so it's always broken),
https://github.com/rndusr/stig/ is for the development version.

So this is not a bug. But thanks for trying to help out!

**Comment by inkch** [comment]
I've opened this without checking other PR...
Sorry to bother you!

**Comment by rndusr** [comment]
No worries. It's always nice when people care.
And I really should make a new release...

**Pull request closed without merging**
